name: "Voyanti Paneltrack Addon"
description: "Voyanti Paneltrack Addon"
version: "0.0.10"
slug: "paneltrack"
url: "https://github.com/heinrich321/voyanti-paneltrack"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  mqtt_host: "192.168.1.104"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt-users"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "paneltrack"
  modbus_ip: "192.168.1.91"
  modbus_port: 1234
  scan_interval: 10
  debug_output: 0
  device_address_list:
   - 3
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  mqtt_base_topic: str
  modbus_ip: str
  modbus_port: int
  scan_interval: int
  debug_output: int
  device_address_list:
   - int